// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/alac.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameSize     uint32                 `protobuf:"varint,1,opt,name=frame_size,json=frameSize,proto3" json:"frame_size,omitempty"`
	Channels      uint32                 `protobuf:"varint,2,opt,name=channels,proto3" json:"channels,omitempty"`
	Layout        uint32                 `protobuf:"varint,3,opt,name=layout,proto3" json:"layout,omitempty"`
	BitDepth      uint32                 `protobuf:"varint,4,opt,name=bit_depth,json=bitDepth,proto3" json:"bit_depth,omitempty"`
	SampleRate    uint32                 `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proto_alac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proto_alac_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetFrameSize() uint32 {
	if x != nil {
		return x.FrameSize
	}
	return 0
}

func (x *Config) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *Config) GetLayout() uint32 {
	if x != nil {
		return x.Layout
	}
	return 0
}

func (x *Config) GetBitDepth() uint32 {
	if x != nil {
		return x.BitDepth
	}
	return 0
}

func (x *Config) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type EncodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EncodeRequest_Config
	//	*EncodeRequest_PcmChunk
	Payload       isEncodeRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeRequest) Reset() {
	*x = EncodeRequest{}
	mi := &file_proto_alac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeRequest) ProtoMessage() {}

func (x *EncodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeRequest.ProtoReflect.Descriptor instead.
func (*EncodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_alac_proto_rawDescGZIP(), []int{1}
}

func (x *EncodeRequest) GetPayload() isEncodeRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EncodeRequest) GetConfig() *Config {
	if x != nil {
		if x, ok := x.Payload.(*EncodeRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *EncodeRequest) GetPcmChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*EncodeRequest_PcmChunk); ok {
			return x.PcmChunk
		}
	}
	return nil
}

type isEncodeRequest_Payload interface {
	isEncodeRequest_Payload()
}

type EncodeRequest_Config struct {
	Config *Config `protobuf:"bytes,1,opt,name=config,proto3,oneof"` // Send this first to initialize the encoder on the server
}

type EncodeRequest_PcmChunk struct {
	PcmChunk []byte `protobuf:"bytes,2,opt,name=pcm_chunk,json=pcmChunk,proto3,oneof"` // Subsequent raw PCM audio data
}

func (*EncodeRequest_Config) isEncodeRequest_Payload() {}

func (*EncodeRequest_PcmChunk) isEncodeRequest_Payload() {}

type EncodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlacChunk     []byte                 `protobuf:"bytes,1,opt,name=alac_chunk,json=alacChunk,proto3" json:"alac_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeResponse) Reset() {
	*x = EncodeResponse{}
	mi := &file_proto_alac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeResponse) ProtoMessage() {}

func (x *EncodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeResponse.ProtoReflect.Descriptor instead.
func (*EncodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_alac_proto_rawDescGZIP(), []int{2}
}

func (x *EncodeResponse) GetAlacChunk() []byte {
	if x != nil {
		return x.AlacChunk
	}
	return nil
}

var File_proto_alac_proto protoreflect.FileDescriptor

const file_proto_alac_proto_rawDesc = "" +
	"\n" +
	"\x10proto/alac.proto\x12\x04alac\"\x99\x01\n" +
	"\x06Config\x12\x1d\n" +
	"\n" +
	"frame_size\x18\x01 \x01(\rR\tframeSize\x12\x1a\n" +
	"\bchannels\x18\x02 \x01(\rR\bchannels\x12\x16\n" +
	"\x06layout\x18\x03 \x01(\rR\x06layout\x12\x1b\n" +
	"\tbit_depth\x18\x04 \x01(\rR\bbitDepth\x12\x1f\n" +
	"\vsample_rate\x18\x05 \x01(\rR\n" +
	"sampleRate\"a\n" +
	"\rEncodeRequest\x12&\n" +
	"\x06config\x18\x01 \x01(\v2\f.alac.ConfigH\x00R\x06config\x12\x1d\n" +
	"\tpcm_chunk\x18\x02 \x01(\fH\x00R\bpcmChunkB\t\n" +
	"\apayload\"/\n" +
	"\x0eEncodeResponse\x12\x1d\n" +
	"\n" +
	"alac_chunk\x18\x01 \x01(\fR\talacChunk2N\n" +
	"\vAlacEncoder\x12?\n" +
	"\fEncodeStream\x12\x13.alac.EncodeRequest\x1a\x14.alac.EncodeResponse\"\x00(\x010\x01B9Z7github.com/lucianari/alac-encoder-rs-lucianari/go/protob\x06proto3"

var (
	file_proto_alac_proto_rawDescOnce sync.Once
	file_proto_alac_proto_rawDescData []byte
)

func file_proto_alac_proto_rawDescGZIP() []byte {
	file_proto_alac_proto_rawDescOnce.Do(func() {
		file_proto_alac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_alac_proto_rawDesc), len(file_proto_alac_proto_rawDesc)))
	})
	return file_proto_alac_proto_rawDescData
}

var file_proto_alac_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_alac_proto_goTypes = []any{
	(*Config)(nil),         // 0: alac.Config
	(*EncodeRequest)(nil),  // 1: alac.EncodeRequest
	(*EncodeResponse)(nil), // 2: alac.EncodeResponse
}
var file_proto_alac_proto_depIdxs = []int32{
	0, // 0: alac.EncodeRequest.config:type_name -> alac.Config
	1, // 1: alac.AlacEncoder.EncodeStream:input_type -> alac.EncodeRequest
	2, // 2: alac.AlacEncoder.EncodeStream:output_type -> alac.EncodeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_alac_proto_init() }
func file_proto_alac_proto_init() {
	if File_proto_alac_proto != nil {
		return
	}
	file_proto_alac_proto_msgTypes[1].OneofWrappers = []any{
		(*EncodeRequest_Config)(nil),
		(*EncodeRequest_PcmChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_alac_proto_rawDesc), len(file_proto_alac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_alac_proto_goTypes,
		DependencyIndexes: file_proto_alac_proto_depIdxs,
		MessageInfos:      file_proto_alac_proto_msgTypes,
	}.Build()
	File_proto_alac_proto = out.File
	file_proto_alac_proto_goTypes = nil
	file_proto_alac_proto_depIdxs = nil
}
