// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/alac.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlacEncoder_EncodeStream_FullMethodName = "/alac.AlacEncoder/EncodeStream"
)

// AlacEncoderClient is the client API for AlacEncoder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlacEncoderClient interface {
	// Encodes a stream of raw PCM audio into ALAC frames.
	EncodeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EncodeRequest, EncodeResponse], error)
}

type alacEncoderClient struct {
	cc grpc.ClientConnInterface
}

func NewAlacEncoderClient(cc grpc.ClientConnInterface) AlacEncoderClient {
	return &alacEncoderClient{cc}
}

func (c *alacEncoderClient) EncodeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EncodeRequest, EncodeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AlacEncoder_ServiceDesc.Streams[0], AlacEncoder_EncodeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EncodeRequest, EncodeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AlacEncoder_EncodeStreamClient = grpc.BidiStreamingClient[EncodeRequest, EncodeResponse]

// AlacEncoderServer is the server API for AlacEncoder service.
// All implementations must embed UnimplementedAlacEncoderServer
// for forward compatibility.
type AlacEncoderServer interface {
	// Encodes a stream of raw PCM audio into ALAC frames.
	EncodeStream(grpc.BidiStreamingServer[EncodeRequest, EncodeResponse]) error
	mustEmbedUnimplementedAlacEncoderServer()
}

// UnimplementedAlacEncoderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlacEncoderServer struct{}

func (UnimplementedAlacEncoderServer) EncodeStream(grpc.BidiStreamingServer[EncodeRequest, EncodeResponse]) error {
	return status.Error(codes.Unimplemented, "method EncodeStream not implemented")
}
func (UnimplementedAlacEncoderServer) mustEmbedUnimplementedAlacEncoderServer() {}
func (UnimplementedAlacEncoderServer) testEmbeddedByValue()                     {}

// UnsafeAlacEncoderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlacEncoderServer will
// result in compilation errors.
type UnsafeAlacEncoderServer interface {
	mustEmbedUnimplementedAlacEncoderServer()
}

func RegisterAlacEncoderServer(s grpc.ServiceRegistrar, srv AlacEncoderServer) {
	// If the following call panics, it indicates UnimplementedAlacEncoderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlacEncoder_ServiceDesc, srv)
}

func _AlacEncoder_EncodeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AlacEncoderServer).EncodeStream(&grpc.GenericServerStream[EncodeRequest, EncodeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AlacEncoder_EncodeStreamServer = grpc.BidiStreamingServer[EncodeRequest, EncodeResponse]

// AlacEncoder_ServiceDesc is the grpc.ServiceDesc for AlacEncoder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlacEncoder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alac.AlacEncoder",
	HandlerType: (*AlacEncoderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EncodeStream",
			Handler:       _AlacEncoder_EncodeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/alac.proto",
}
